defaults:
    - _self_
    - dataset: dune2d
distributed: true
iterations: 50
minibatch_size: 2
id: ???
output_dir: output/${id}/${dataset.name}/${minibatch_size}/${dataset.output_shape}_out/${dataset.input_shape}_in/
