name:           "cosmic_tagger_sparse"
data_directory: /lus/grand/projects/datascience/cadams/datasets/SBND/
file:           "cosmic_tagging_train.h5"
dimension:      2
channels:       [0,1,2]
producer:       "sbndwire"
output_shape:   "dense"
